#!/bin/bash
# Setup script for frontend environment variables

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

echo "🔧 Setting up frontend environment variables..."
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Aborted. Keeping existing .env.local"
        exit 0
    fi
fi

# Production backend URL
BACKEND_URL="https://xezfenhu6t.us-east-1.awsapprunner.com"

# Ask user for environment
echo "Select environment:"
echo "1) Local development (http://localhost:8000)"
echo "2) Production backend ($BACKEND_URL)"
read -p "Enter choice [1-2] (default: 1): " choice
choice=${choice:-1}

if [ "$choice" == "1" ]; then
    SELECTED_URL="http://localhost:8000"
    echo "✅ Using local development backend"
else
    SELECTED_URL="$BACKEND_URL"
    echo "✅ Using production backend"
fi

# Create .env.local
cat > .env.local << EOF
# Frontend Environment Variables
# Generated by setup_env.sh
# DO NOT commit this file to git

# Backend API URL
NEXT_PUBLIC_BACKEND_URL=$SELECTED_URL
EOF

echo ""
echo "✅ Created .env.local with:"
echo "   NEXT_PUBLIC_BACKEND_URL=$SELECTED_URL"
echo ""
echo "📝 Next steps:"
echo "   1. Review .env.local if needed"
echo "   2. Run 'npm run dev' to start development server"
echo "   3. The backend URL will be used automatically"
echo ""
