#!/bin/bash
# Setup script for frontend environment variables.
# Auto-detects the git branch to offer the right remote backend URL.

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

echo "🔧 Setting up frontend environment variables..."
echo ""

if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Aborted. Keeping existing .env.local"
        exit 0
    fi
fi

PROD_BACKEND_URL="https://xezfenhu6t.us-east-1.awsapprunner.com"
DEV_BACKEND_URL="${TRIPY_DEV_BACKEND_URL:-https://vi3dh2q9ic.us-east-1.awsapprunner.com}"

BRANCH=$(git -C "$SCRIPT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
echo "Detected branch: $BRANCH"
echo ""

if [ "$BRANCH" = "dev" ] && [ -n "$DEV_BACKEND_URL" ]; then
    echo "Select environment:"
    echo "1) Local development (http://localhost:8000)"
    echo "2) Dev backend ($DEV_BACKEND_URL)"
    read -p "Enter choice [1-2] (default: 1): " choice
    choice=${choice:-1}
    if [ "$choice" == "2" ]; then
        SELECTED_URL="$DEV_BACKEND_URL"
        echo "✅ Using dev backend"
    else
        SELECTED_URL="http://localhost:8000"
        echo "✅ Using local development backend"
    fi
elif [ "$BRANCH" = "main" ]; then
    echo "Select environment:"
    echo "1) Local development (http://localhost:8000)"
    echo "2) Production backend ($PROD_BACKEND_URL)"
    read -p "Enter choice [1-2] (default: 1): " choice
    choice=${choice:-1}
    if [ "$choice" == "2" ]; then
        SELECTED_URL="$PROD_BACKEND_URL"
        echo "✅ Using production backend"
    else
        SELECTED_URL="http://localhost:8000"
        echo "✅ Using local development backend"
    fi
else
    echo "Select environment:"
    echo "1) Local development (http://localhost:8000)"
    echo "2) Production backend ($PROD_BACKEND_URL)"
    if [ -n "$DEV_BACKEND_URL" ]; then
        echo "3) Dev backend ($DEV_BACKEND_URL)"
    fi
    read -p "Enter choice [1-2] (default: 1): " choice
    choice=${choice:-1}
    if [ "$choice" == "2" ]; then
        SELECTED_URL="$PROD_BACKEND_URL"
        echo "✅ Using production backend"
    elif [ "$choice" == "3" ] && [ -n "$DEV_BACKEND_URL" ]; then
        SELECTED_URL="$DEV_BACKEND_URL"
        echo "✅ Using dev backend"
    else
        SELECTED_URL="http://localhost:8000"
        echo "✅ Using local development backend"
    fi
fi

cat > .env.local << EOF
# Frontend Environment Variables
# Generated by setup_env.sh (branch: $BRANCH)
# DO NOT commit this file to git

NEXT_PUBLIC_BACKEND_URL=$SELECTED_URL
EOF

echo ""
echo "✅ Created .env.local with:"
echo "   NEXT_PUBLIC_BACKEND_URL=$SELECTED_URL"
echo ""
echo "📝 Next steps:"
echo "   1. Review .env.local if needed"
echo "   2. Run 'npm run dev' to start development server"
echo ""
